////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    elven_nft_minter
    (
        callBack
        changeBaseCids
        claimScFunds
        clearAllowlist
        disableAllowlist
        enableAllowlist
        getAllowlistAddressCheck
        getAllowlistSize
        getCollectionTokenName
        getDropTokensLeft
        getFileExtension
        getFilename
        getMintedPerAddressPerDrop
        getMintedPerAddressTotal
        getNftPrice
        getNftTokenId
        getNftTokenName
        getProvenanceHash
        getTokenNameSuffix
        getTokensLimitPerAddressPerDrop
        getTokensLimitPerAddressTotal
        getTotalSupply
        getTotalSupplyOfCurrentDrop
        getTotalTokensLeft
        giveaway
        isAllowlistEnabled
        isDropActive
        isMintingPaused
        issueToken
        pauseMinting
        populateIndexes
        setFilename
        removeAllowlistAddress
        setDrop
        setLocalRoles
        setNewTokensLimitPerAddress
        shuffle
        startMinting
    )
}
